from sqlalchemy import Integer, String, DateTime, ForeignKey, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from shared.database import Base
import uuid

class UserAvailability(Base):
    """
    Stores recurring available time slots for a user.
    We use ISO weekday numbers (1=Monday, 7=Sunday) or Strings. 
    Let's use Strings for readability in Admin: 'Monday', 'Tuesday', etc.
    """
    __tablename__ = "user_availability"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    day_of_week: Mapped[str] = mapped_column(String, nullable=False)  # "Monday", "Tuesday"...
    start_time: Mapped[str] = mapped_column(String, nullable=False)   # Format "HH:MM" (24h)
    end_time: Mapped[str] = mapped_column(String, nullable=False)     # Format "HH:MM" (24h)

class GeneratedSchedule(Base):
    """
    The final schedule output generated by the algorithm.
    Links a specific Task to a specific Time Slot.
    """
    __tablename__ = "generated_schedules"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    
    # Owner of the schedule
    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # The Task being worked on
    task_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False)
    
    # The specific date and time assigned (e.g., 2025-11-24 18:00:00)
    scheduled_start: Mapped[str] = mapped_column(DateTime(timezone=True), nullable=False)
    scheduled_end: Mapped[str] = mapped_column(DateTime(timezone=True), nullable=False)
    
    # Explanation for why this slot was chosen (Requirement from User Story)
    reasoning: Mapped[str] = mapped_column(Text, nullable=True)
    
    # Status to track execution
    status: Mapped[str] = mapped_column(String, default="pending", nullable=False) # pending, completed, skipped